# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  mywebapp:
    image: mywebapp-debug
    build:
      context: .
      dockerfile: MyWebApp/debug.Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5196:5196
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
